[env:genericSTM32F103C6]
platform = ststm32
board = genericSTM32F103C6
framework = cmsis
upload_protocol = stlink
debug_tool = stlink
board_build.ldscript = STM32F103C6T6_FLASH.ld
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
    -DSTM32F103x6
